<a href="https://colab.research.google.com/github/aparna-2001/machine_learning_using_python/blob/main/numpy_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# numpy

import numpy as np

#creating a numpy array
a = np.arange(10)
b = np.arange(0,10,2)
c = np.random.random(4)
d = np.random.random((2,3))
e = np.zeros(5)
f = np.zeros((2,3))
g = np.full((3,3),5)
h = np.eye(3)
i = [1,2,3,4,5]
j = np.array(i)


#print(b)
#print(a)
#print(c)
#print(d)
#print(e)
#print(f)
#print(g)
#print(h)
#print(j)


In [3]:
#array indexing

list1 = [1,2,3,4,5]
r1 = np.array(list)

list2 = [6,7,8,9,0]
r2 = np.array([list1, list2])


#shape of the array
print(r2.shape)
print(r2)

#acessing the first row first element
print(r2[0,0])


#access the 2nd row fifth column element
print(r2[1,4])

#access the 4th and fifth element
list3 = [1,2,3,4,5,6]
r4 = np.array(list3)
print(r4[[3,5]])


#access the first 5 elements
list4 = [2,4,6,8,9,1,3]
r5 = np.array(list4)
print(r5[0:5])

r2 = np.array([list1, list2])
print(r2)


(2, 5)
[[1 2 3 4 5]
 [6 7 8 9 0]]
1
0
[4 6]
[2 4 6 8 9]
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [4]:
#boolean indexing

list = [1,2,3,4,5]
r1 = np.array(list)
print(r1>2)
print(r1[r1>2])


[False False  True  True  True]
[3 4 5]


In [5]:
#slicing
list = [[1,2,3,4,5],
        [4,5,6,7,8],
        [9,8,7,6,5]]



r1 = np.array(list)
print(r1.shape)

#last 2 rows and first 2 columns (not based on index language)
print(r1[1:3, 0:3])

#first row onwards and 2nd column onwards (not based on index language)
print(r1[1:, 2:])



#2nd row and all columns (not based on index language)
b4 = r1[2:, 0:]
print(b4.shape)


#2nd row and all columns (not based on index language)
b5 = r1[2,0:]
print(b5)
print(b5.shape)

(3, 5)
[[4 5 6]
 [9 8 7]]
[[6 7 8]
 [7 6 5]]
(1, 5)
[9 8 7 6 5]
(5,)


In [6]:
#reshaping arrays

print(b5.shape)

#reshaping the array into one row and many rows needed by the function
b6 = b5.reshape(1,-1)
print(b6.shape)


#reshaping the array into any rows needed with only one column
b7 = b5.reshape(-1,1)
print(b7)
print(b6)
print(b5)

(5,)
(1, 5)
[[9]
 [8]
 [7]
 [6]
 [5]]
[[9 8 7 6 5]]
[9 8 7 6 5]


In [7]:
#MATHEMATICAL OPERATION OF ARRAYS

#mathematical operations
a = np.array([[1,2],[4,5]])
b = np.array([[7,8],[2,3]])
#print(a+b)
#print(a-b)
#print(a*b)
#print(np.dot(a,b))
#print(a/b)

#to matrix
a_matrix = np.asmatrix(a)
b_matrix = np.asmatrix(b)
#print(a_matrix*b_matrix)
#print(np.dot(a_matrix,b_matrix))

#array dot product and multiplication product would be different, matrix dot product and multiplication product are same

#cumulative sum

c = np.array  ([[1,2,3],[4,5,6],[7,8,9]])
print(a.cumsum())

[ 1  3  7 12]


In [8]:

#1. Create an array

    #Create a NumPy array containing numbers from 5 to 14
    #Print its shape.

a = np.arange(5,15)
print(a.shape)





(10,)
[ 0  4  8 12 16 20]
(6,)


In [9]:
#2

b = np.arange(0,21,4)
print(b)
print(b.shape)

[ 0  4  8 12 16 20]
(6,)


In [10]:
#3
c = np.zeros((3,4))
print(c[1,2])

0.0


In [20]:
#4
d = np.full((4,4),7)
print(d)
print(d[0,0])
print(d[1,1])
print(d[2,2])
print(d[3,3])

print(np.diagonal(d))

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
7
7
7
7
[7 7 7 7]


In [22]:
#5

e = np.eye(5)
print(e[3,3])

1.0
