<a href="https://colab.research.google.com/github/aparna-2001/machine_learning_using_python/blob/main/numpy_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# numpy

import numpy as np

#creating a numpy array
a = np.arange(10)
b = np.arange(0,10,2)
c = np.random.random(4)
d = np.random.random((2,3))
e = np.zeros(5)
f = np.zeros((2,3))
g = np.full((3,3),5)
h = np.eye(3)
i = [1,2,3,4,5]
j = np.array(i)


#print(b)
#print(a)
#print(c)
#print(d)
#print(e)
#print(f)
#print(g)
#print(h)
#print(j)


In [22]:
#array indexing

list1 = [1,2,3,4,5]
r1 = np.array(list)

list2 = [6,7,8,9,0]
r2 = np.array([list1, list2])


#shape of the array
print(r2.shape)
print(r2)

#acessing the first row first element
print(r2[0,0])


#access the 2nd row fifth column element
print(r2[1,4])

#access the 4th and fifth element
list3 = [1,2,3,4,5,6]
r4 = np.array(list3)
print(r4[[3,5]])


#access the first 5 elements
list4 = [2,4,6,8,9,1,3]
r5 = np.array(list4)
print(r5[0:5])

r2 = np.array([list1, list2])
print(r2)


[[1 2 3 4 5]
 [6 7 8 9 0]]
[[1]]


In [46]:
#boolean indexing

list = [1,2,3,4,5]
r1 = np.array(list)
print(r1>2)
print(r1[r1>2])


[False False  True  True  True]
[3 4 5]
(3, 5)
(1, 5)
[9 8 7 6 5]
(5,)


In [ ]:
#slicing
list = [[1,2,3,4,5],
        [4,5,6,7,8],
        [9,8,7,6,5]]



r1 = np.array(list)
print(r1.shape)

#last 2 rows and first 2 columns (not based on index language)
print(r1[1:3, 0:3])

#first row onwards and 2nd column onwards (not based on index language)
print(r1[1:, 2:])



#2nd row and all columns (not based on index language)
b4 = r1[2:, 0:]
print(b4.shape)


#2nd row and all columns (not based on index language)
b5 = r1[2,0:]
print(b5)
print(b5.shape)

In [62]:
#reshaping arrays

print(b5.shape)

#reshaping the array into one row and many rows needed by the function
b6 = b5.reshape(1,-1)
print(b6.shape)


#reshaping the array into any rows needed with only one column
b7 = b5.reshape(-1,1)
print(b7)
print(b6)
print(b5)

(5,)
(1, 5)
[[9]
 [8]
 [7]
 [6]
 [5]]
[[9 8 7 6 5]]
[9 8 7 6 5]


#EXCERCISES


### **Exercises**

1. **Create an array**

   * Create a NumPy array containing numbers from **5 to 14**.
   * Print its shape.

2. **Step-based array**

   * Create an array from **0 to 20** with a step of **4**.
   * Print the array and its length.

3. **2D zeros**

   * Create a **3×4** array filled with zeros.
   * Access the element at **2nd row, 3rd column**.

4. **Full matrix**

   * Create a **4×4** array filled with the value **7**.
   * Print the diagonal elements using indexing.

5. **Identity matrix**

   * Create an identity matrix of size **5×5**.
   * Access the element at position **(3,3)**.

6. **Row & column slicing**

   * Given

     ```
     A = [[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]]
     ```
   * Extract:

     * last two rows
     * first two columns

7. **Boolean indexing**

   * Given `x = [3, 6, 1, 8, 4, 9]`
   * Extract all values **greater than 5**.

8. **Fancy indexing**

   * Given `y = [10, 20, 30, 40, 50, 60]`
   * Extract the **2nd, 4th, and 6th** elements using index arrays.

9. **Reshape to row & column**

   * Given `z = [1,2,3,4,5,6]`
   * Reshape it into:

     * one row
     * one column

10. **Shape comparison**

    * From Exercise 9, print and compare:

      * shape of original array
      * shape of row reshaped array
      * shape of column reshaped array




In [ ]:
#MATHEMATICAL OPERATION OF ARRAYS

#mathematical operations
a = np.array([[1,2],[4,5]])
b = np.array([[7,8],[2,3]])
#print(a+b)
#print(a-b)
#print(a*b)
#print(np.dot(a,b))
#print(a/b)

#to matrix
a_matrix = np.asmatrix(a)
b_matrix = np.asmatrix(b)
#print(a_matrix*b_matrix)
#print(np.dot(a_matrix,b_matrix))

#array dot product and multiplication product would be different, matrix dot product and multiplication product are same

#cumulative sum

c = np.array  ([[1,2,3],[4,5,6],[7,8,9]])
print(a.cumsum())